version: '3'
services:
  notebook:
    build: .
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    command: >
      bash -c "
      rm .cache/matplotlib/fontlist-v330.json &&
      start-notebook.sh --NotebookApp.token=""
      "
